### ISSUE TITLE
בדיקת מטלה 7

### ISSUE THREAD

**Issue by michael-lemberger** [L-VideoGames/foodPyramid#1]
מרגיש שאין באמת תהליך פתיחה, כי בשום שלב לא מוסבר לשחקן מה המטרה שלו במשחק.
בנוסף, במטלה השבועית, שאלה ג' ביקשו למצוא מסלול הכי מהיר. שים לב שזה לא מה שביצעת בפועל

**Comment by LIADN7** [comment]
סידרתי את המשחק ב3 מימדים ועשיו זה מסודר כמו שצריך כולל הסבר למשתמש ומעבר בין סצנות,
ובמטלה השבועית סידרתי את המובר של העכבר...
תודה!
