### ISSUE TITLE
צריך להוסיף הסברים

### ISSUE THREAD

**Issue by erelsgl** [L-VideoGames/foodPyramid#2]
כשהשחקן אוכל משהו, צריך להסביר לו מה הוא עשה. למשל "אכלת חלבון, כל הכבוד!". לפחות בפעמים הראשונות.

כרגע רואים ציורים למטה, אבל המשמעות שלהם לא ברורה; צריך להוסיף 
tooltip
שאומר "זו רמת החלבונים הנוכחית שלך".

**Comment by LIADN7** [comment]
טופל
